### ISSUE TITLE
Pesquisar no site da prefeitura municipal de João Pessoa quais bases de educação

### ISSUE THREAD

**Issue by mrafaelbatista** [AIDA-Uniesp/mapeamento_de_bases_de_dados_publicos_da_paraiba#4]
- [x] Listar as bases de dados
- [x] Verificar quais bases de dados assuntos

**Comment by thaywanep** [comment]
@mrafaelbatista Não foi encontrada base de dados educacionais no site da transparência de João Pessoa e no site da transparência da Paraíba.

Foi encontrada uma base nacional de dados do Enem 2022 no site do INEP.
